package model;

public enum Direction {
    POS_HORIZONTAL,
    POS_VERTICAL,
    POS_HORIZONTAL_AND_POS_VERTICAL,
    NEG_HORIZONTAL,
    NEG_VERTICAL,
    NEG_HORIZONTAL_AND_NEG_VERTICAL,
    POS_HORIZONTAL_AND_NEG_VERTICAL,
    NEG_HORIZONTAL_AND_POS_VERTICAL
}
